SET DEFINE OFF;

-- ====================================================================
-- TABLE A: Fixed Income yields, curves, and major commodity pegs
-- ====================================================================
CREATE TABLE MACRO_COUNTERWEIGHTS (
    counterweight_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol_code         VARCHAR2(25) NOT NULL,
    asset_description   VARCHAR2(100) NOT NULL,
    current_yield_spot  NUMBER(12, 4) NOT NULL,
    net_basis_change    NUMBER(12, 4) NOT NULL,
    pct_change          NUMBER(5, 2) NOT NULL,
    last_updated        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_MACRO_CODE ON MACRO_COUNTERWEIGHTS (symbol_code);

-- ====================================================================
-- TABLE B: Structural bank parameters mapping the V4 acceleration floors
-- ====================================================================
CREATE TABLE BANK_INFLECTION_MATRIX (
    matrix_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_code         VARCHAR2(10) NOT NULL,
    company_name        VARCHAR2(100) NOT NULL,
    structural_floor    NUMBER(12, 4) NOT NULL,
    rc_threshold        NUMBER(8, 4) NOT NULL,
    target_ceiling_1    NUMBER(12, 4) NOT NULL,
    target_ceiling_2    NUMBER(12, 4) NOT NULL
);

CREATE INDEX IDX_BANK_MATRIX_CODE ON BANK_INFLECTION_MATRIX (ticker_code);

-- ====================================================================
-- DIAGNOSTIC & ANALYTICAL QUERIES
-- ====================================================================

-- Query 1: Big Tech Intraday Sector Tracking
SELECT 
    ticker_code, 
    price_last_close, 
    net_change, 
    pct_change, 
    direction
FROM 
    MARKET_TICKS
WHERE 
    ticker_code IN ('GOOGL', 'GOOG', 'MU', 'NVDA', 'AMZN', 'AMD', 'INTC', 'COST', 'PG', 'AVGO', 'MSFT', 'AAPL', 'TSLA', 'META', 'ORCL', 'AMAT', 'XOM')
ORDER BY 
    pct_change DESC;

-- Query 2: Financial Sector Forward Projections (Deduplicated Structure)
-- Adjust temporal filters / row partitions as needed to avoid Cartesian duplication
SELECT DISTINCT
    f20.ticker_code || ' | ' || 
    TO_CHAR(f36.base_price, '999.99') || ' | ' || 
    TO_CHAR(f36.projected_target, '999.99') || ' | ' || 
    f36.expected_return_pct || '% | ' || 
    f20.engine_classification AS "BLOOMBERG FINANCIAL REPORT"
FROM 
    FACT_TELEMETRY_ASSET_SPOT f20
JOIN (    
    SELECT 
        ticker_code, 
        base_price, 
        projected_target, 
        expected_return_pct
    FROM 
        MARKET_FORWARD_PROJECTIONS 
    WHERE 
        horizon_months = 36
) f36 ON f20.ticker_code = f36.ticker_code
WHERE 
    f20.ticker_code IN ('MS', 'JPM', 'WFC', 'HSBC', 'BK', 'NU', 'ITUB', 'BSBR');
